# Configuration de la base de données PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/geoquiz
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate configuration
# 'update' crée ou met à jour les tables automatiquement selon vos entités
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8081